### ISSUE TITLE
[Feature request] Support multiple game types, one per map

### ISSUE THREAD

**Issue by ClobberXD** [rubenwardy/capturetheflag#190] opened 2018-08-06 05:18 UTC
I've seen quite a few PvP games in which there are many "game-types" out of which one is randomly selected for the current match. I propose to make CTF one of the game-types, so there'd be game-types like
- Team Death-match
  - Two teams go on a killing spree, and the team with the higher total score at the end of `t` minutes wins.
  - Players will be given a default set of weapons on (re)spawn, to keep things equal.
- Last man standing
  - No teams, it's all vs. all. Players would be spawned at random places throughout the map (surface only).
  - Players will be granted a set of default weapons on (re)spawn.
  - Keep clobbering for `t` minutes. Player with the highest score wins.
- Capture the flag
  - The original CTF experience.
  - Instead of one capture to end, it could be modified so that the team which reaches 5 captures first, wins.
- (More to come)

Yes this certainly makes CTF (the game) more complicated, but I feel that it will be very engaging and thrilling for the players.

****

I've already gotten a few ideas about the implementation:
- Game-type could be set using a `game_type` field in `map.conf`.
- All of the suggested functionality can either be added to `ctf_match` itself, or can become a separate mod (`ctf_game_types` maybe?).
- Some of the player stats (like `kills`, `deaths`, `K/D`, etc.) will persist across all game-types, while those like `captures` and `attempts` would be game-type-specific.

Will proceed if this is agreed to be a good concept :)

**Comment by CLtheman1** [comment] 2018-08-15 13:42
Well then it wouldn't exactly be "capture the flag." The server would have to be renamed if they added this.

**Comment by rubenwardy** [comment] 2018-08-15 13:44
duplicate of https://github.com/rubenwardy/capturetheflag/issues/71

**Closed** 2018-08-15 13:43 UTC
