### ISSUE TITLE
Add mines and spikes

### ISSUE THREAD

**Issue by farooqkz** [rubenwardy/capturetheflag#150] opened 2018-04-14 13:53 UTC
Mines explode when enemies walk on them.
Spikes damage the player on them.
Two other suggestion:
 - Think about number of mines, they could put heavy load on the server.
 - Owner of a mine or a spike is team of the player who has placed them. e.g. they even damage Red players when they are in the Red's side.

**Comment by rubenwardy** [comment] 2018-04-14 14:53
Duplicate of #35

**Closed by rubenwardy** 2018-04-14 14:53 UTC
